project:
  type: book
  output-dir: ../docs

book:
  title: "Minería de Datos"
  subtitle: "ITAM 2025"
  author: "Saúl Caballero"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - 00-requerimientos-computacion.qmd
    - 01-introduccion.qmd
    - 02-principios.qmd
    - part: "Regresion lineal"
      chapters: 
        - 03-regresion_lineal.qmd
        - violaciones_supuestos_regresion.ipynb
        - analisis_advertising_dataset.ipynb
        - ejercicio_wine_quality.ipynb
    - 04-clasificacion.qmd
    - 05-arboles.qmd
    - references.qmd
    - part: "Ejemplos"
      chapters:
        - introduccion.ipynb
        - regresion_lineal.ipynb
  open-graph: true

bibliography: references.bib

execute:
  freeze: auto
  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    lang: es
    font-size: 1.1em
    number-sections: false



